### ISSUE TITLE
密集度圖表 y 軸標題改為大寫

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#1]
首頁分數 -> 密集度圖表 -> 左上角 y 軸標題改為大寫 CM

**Comment by augusWuDotan** [comment]
Solve 請確認

**Comment by dohProject** [comment]
目前版本看起來沒解
![Alt text](https://i.imgur.com/ogckZAu.jpg)

**Comment by dohProject** [comment]
另請將01遊戲的y軸標題改為 AVG
![Alt text](https://i.imgur.com/sXxcLoM.jpg)

**Comment by augusWuDotan** [comment]
commit 'MyScore textAllCaps CM'
try again
