### ISSUE TITLE
排行榜，資料與預期不符

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#11]
請確認 /Match/getLeaderBoard 這支 API 與相應內容
1. 數值顯示不正確：
iOS 這裡分數第一名到第三名分別為 180.0、175.5、175.5
Android 目前小數點後面沒有顯示
2. 筆數不正確
以 01遊戲為例，Android 只顯示了 3 筆，iOS 有顯示 20 筆，這邊查看 API 應該是有確實回 20 筆
<a href="https://imgur.com/8OKinyw"><img src="https://i.imgur.com/8OKinyw.png" title="source: imgur.com" /></a>

**Comment by augusWuDotan** [comment]
完成，請檢查

**Comment by dohProject** [comment]
由於 rank 有並列問題，例如現在米老鼠有大量並列第 2 的資料，請讓 rank 為 1, 2, 3 的資料都顯示對應的獎盃，其餘的就照舊顯示

**Comment by augusWuDotan** [comment]
請再確認
