### ISSUE TITLE
戰績內容頁沒有正確顯示

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#12]
該筆戰績畫面是空的，iOS 這邊正常
可用 tenvunchi@gmail.com 登入，按時間找該筆戰績
<a href="https://imgur.com/P6pH4uD"><img src="https://i.imgur.com/P6pH4uD.png" title="source: imgur.com" /></a>

**Comment by augusWuDotan** [comment]
完成！請檢查
