### ISSUE TITLE
玩家封面照片與 placeHolder 重疊

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#13]
發生於首次開啟 App 登入後
<a href="https://imgur.com/XUe0Twy"><img src="https://i.imgur.com/XUe0Twy.png" title="source: imgur.com" /></a>

**Comment by augusWuDotan** [comment]
請確認

**Comment by dohProject** [comment]
placeHolder 看起來沒有經過圓角處理 每次進入頁面後會有很明顯的畫面衝突感
