### ISSUE TITLE
地區店家需要增加"所有"選項

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#14]
除了"國家"層級以外，其餘地區層級第一個選項固定為 "所有"
選擇該選項後，將上一層的 regionId 代去 call API 就可以取得該地區所有店家，
以中華台北為例，選擇了中華台北的 "所有"，就將中華台北的 regionId 代去

所有的文字翻譯
繁簡中: "所有"
英日德: "All"

<a href="https://imgur.com/KxXSJpl"><img src="https://i.imgur.com/KxXSJpl.png" title="source: imgur.com" /></a>

**Comment by augusWuDotan** [comment]
已經新增
