### ISSUE TITLE
隊伍戰績也改為使用隊伍 button 切換

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#15]
隊伍戰績的隊伍切換也改為與內容頁相似的下方按鈕切換隊伍
中間的隊伍成績區塊每次只顯示一隊，切換按鈕時更新資料

此外，上方面板的 score / score2 原先在 team 層級，
移至 teams 內層，如此就能根據切換的隊伍更新，
teams 內也會新增了 isWin 欄位，=true 時顯示皇冠

<a href="https://imgur.com/FkiVKeD"><img src="https://i.imgur.com/FkiVKeD.png" title="source: imgur.com" /></a>

**Comment by augusWuDotan** [comment]
已經新增
