### ISSUE TITLE
count-up 類型的戰績內容頁，下方按鈕也顯示比數

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#16]
比照先前的 cricket 修改，在玩家的名稱後綴上分數

**Comment by augusWuDotan** [comment]
好了

**Comment by dohProject** [comment]
發現有一筆戰績排序錯誤，導致下方的比分也是錯誤的
帳號 tenvunchu@gmail.com
<a href="https://imgur.com/uJ6pKs9"><img src="https://i.imgur.com/uJ6pKs9.png" title="source: imgur.com" /></a>

**Comment by augusWuDotan** [comment]
try
