### ISSUE TITLE
隊伍戰績，團隊名稱本地化、文字修改

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#17]
1. Team A、Team B 等文字，繁中顯示 "團隊 A"，簡中顯示 "团队 B"
2. 原先顯示 "Player Name"、"玩家名稱" 的標題去掉名稱，直接顯示 "Player"、"玩家"

<a href="https://imgur.com/w79ZiPK"><img src="https://i.imgur.com/w79ZiPK.png" title="source: imgur.com" /></a>

**Comment by augusWuDotan** [comment]
已經修改
