### ISSUE TITLE
歷史戰績，隊伍頁，資料錯誤

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#4]
隊伍中有三名玩家，目前只顯示出兩位

上方分數面板應顯示 AVG Dart 與其數值，對應到 score、score2、scoreTitle1、scoreTitle2 等欄位，應正確對應顯示。

https://i.imgur.com/inIfGH8.jpg

**Comment by augusWuDotan** [comment]
這個可以先給我整筆的資料 json 嗎？

**Comment by dohProject** [comment]
範例資料可參考
https://testapi.fidodarts.com/Match/getBattleDetail?confirmCode=4152A74BCA71FDE6B16EE316A7E703EB&gameType=1&isTeamMode=false&matchId=a87e0e8d-01e1-11ea-916f-061b34b5c3af&playerId=dc910198-b624-11e6-a693-0242ac110005
或直接在帳號內用日期找到該筆戰績

<img src="https://i.imgur.com/qrSQ4Wh.jpg" width="320px" height="576px">
<img src="https://i.imgur.com/8FWBF3B.png" width="320px" height="576px">

**Comment by augusWuDotan** [comment]
請再檢查一次！感恩

**Comment by dohProject** [comment]
仍然有錯
1. 玩家名稱處不需要藍色背景，維持白色即可，僅有 Player Name 標題需有背景
2. 上方面板的分數仍然不正確
3. 日期分隔號使用 "-" 取代 "~"

請對照我上方第一張 iOS 的畫面

**Comment by augusWuDotan** [comment]
1 close
2 close
3 close

**Comment by dohProject** [comment]
日期格式仍然不正確 應為 yyyy/MM/dd hh:mm - hh:mm
現在為 yyyy-MM-dd hh:mm - hh:mm
請與 iOS 畫面確實對照
