### ISSUE TITLE
歷史戰績，內容頁，多項問題

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#5]
1. API 內容有些欄位需要為空字串不顯示，以 DoubleRight 11/11 13:46 這筆戰績為例，下方仍要能正常顯示，現在為全空
https://i.imgur.com/EJLCuzR.jpg

2. 每一 round 請依據 index 進行排序，現在應該是按照 API 回傳順序直接顯示

3. 對戰時間統一格式化至分，現在有的會跑到秒

4. Round roundScore 與 gameScore 等分數欄位直接呈現 API 端回傳字串即可，不需要轉換數字（大多數分數類型的欄位都已經改型別為字串，以方便直接呈現）

5. 點擊下方隊伍選項時，若該隊伍的按鈕未完整顯示，請自動捲動使其能完整顯示

**Comment by augusWuDotan** [comment]
1.
json 裡面有很多個  [key] =, 會導致 頗析json 失敗
----
最好的解決方式 [key]="" or [key] = null or [ non key ]
暫時解決...

**Comment by augusWuDotan** [comment]
-
2. 沒有問題
-
3. solve 列表 and 歷史戰績
-
4. 資料格式與輸出內容要注意規範
-
5. 因該已經解決，請再確認

**Comment by dohProject** [comment]
round 第二行文字請填入 API 新欄位 gameScoreTitle，原先應該是與上方欄位相同，現在需要區分開來。以下兩圖為例，這個欄位目前為空，所以 iOS 這邊可以空掉，Android 則還會顯示 H.R.
<img src="https://i.imgur.com/3Hp0WnC.jpg" width="320px" height="576px">
<img src="https://i.imgur.com/EAt5B5r.png" width="320px" height="576px">

**Comment by dohProject** [comment]
內容錯誤部分
頁面可參考
https://testapi.fidodarts.com/Match/getBattleDetail?confirmCode=B15766A561FB5ABDF23E63D939489C67&gameType=1&isTeamMode=true&matchId=756e736b-046c-11ea-916f-061b34b5c3af&playerId=dc910198-b624-11e6-a693-0242ac110005
上方分數欄位錯誤，API 內確實有回 16.5
ROUND 內數值也請直接填 API 給的，應沒有小數點
文字小問題，Round 請改全大寫，日期 format 中間分隔符號請用 -
<img src="https://i.imgur.com/ZKUQRTq.jpg" width="320px" height="576px">
<img src="https://i.imgur.com/i9CTW45.png" width="320px" height="576px">

**Comment by dohProject** [comment]
切換玩家時，上方面板的分數也應該隨之更新
<img src="https://i.imgur.com/pHspYNM.jpg" width="320px" height="576px">
<img src="https://i.imgur.com/9fh9VJ5.png" width="320px" height="576px">

**Comment by dohProject** [comment]
選擇玩家後自動滾動，目前我手上這支操作看起來還是沒有，效果請參考
https://i.imgur.com/6mja6UY.mp4

**Comment by augusWuDotan** [comment]
已經全數搞定 請再次檢查！

**Comment by dohProject** [comment]
1. 日期格式請用 yyyy/MM/dd hh:mm - hh:mm
2. 目前畫面中寫死的 Round 都改為全大寫 ROUND，另請檢查列表、隊伍頁是否還有含小寫的 Round

**Comment by augusWuDotan** [comment]
1.close
2.close

**Comment by dohProject** [comment]
日期格式仍然不正確 應為 yyyy/MM/dd hh:mm - hh:mm
現在為 yyyy-MM-dd hh:mm - hh:mm
請與 iOS 畫面確實對照
