### ISSUE TITLE
首頁分數圖表數據分佈

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#8]
01遊戲
上限提高至 100

米老鼠
上限提高至 5.0

高分賽
上限提高至 1000
(y 軸分數不需顯示小數點.0，整數即可)

密集度
上限提高至 20
每隔間距為 4

![Alt text](https://i.imgur.com/qzw2kLr.png)
![Alt text](https://i.imgur.com/6SAg2g2.png)
![Alt text](https://i.imgur.com/ddqKGJl.png)
![Alt text](https://i.imgur.com/MZfTm7S.png)

**Comment by augusWuDotan** [comment]
暫時搞定，請再確認

**Comment by dohProject** [comment]
01遊戲的y軸標題，請改為AVG

**Comment by augusWuDotan** [comment]
請再確認
