### ISSUE TITLE
讓分場次須顯示 H icon

### ISSUE THREAD

**Issue by dohProject** [dohProject/FIDODARTS_Android_issue#9]
請確認戰績相關三支 API 應該都有一個欄位 isMatchHandicap
為 true 時，需要在畫面上顯示 H icon 如下
<a href="https://imgur.com/C3QcL1R"><img src="https://i.imgur.com/C3QcL1R.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/fODFeSk"><img src="https://i.imgur.com/fODFeSk.png" title="source: imgur.com" /></a>
隊伍戰績也有，位置與內容頁相同
可使用帳號
tenvunchi@gmail.com
1
登入找到 isMatchHandicap=true 的戰績

H icon
@2x
https://imgur.com/BidSDRX
@3x
https://imgur.com/tfYnGim

**Comment by augusWuDotan** [comment]
已經解決！請幫忙看看哪些漏掉
